launchConfigName:
  Type: AWS::AutoScaling::LaunchConfiguration
  Properties:
    LaunchConfigurationName:
    AssociatePublicIpAddress: true|false
    IamInstanceProfile:
    ImageId:
    EbsOptimized: true|false
    InstanceMonitoring: true|false
    InstanceType: "t3.medium"
    KernelId:
    KeyName:
    SecurityGroups:
      - sg-id
    UserData:
      Fn::Base64: !Sub #!/bin/bash -ex # your script here


    BlockDeviceMapping:
      - DevieName: "/dev/sdk"
        Ebs:
          - VolumeSize: "10"
